2015-02-12 12:54:57,423 - INFO     - main.py             :14 - starting sync daemon
2015-02-12 12:54:57,423 - WARNING  - syncCassElastic.py  :19 - No config file passed for the sync class
2015-02-12 12:55:18,990 - INFO     - main.py             :14 - starting sync daemon
2015-02-12 12:56:57,437 - INFO     - main.py             :14 - starting sync daemon
2015-02-12 13:00:00,216 - INFO     - main.py             :14 - starting sync daemon
2015-02-12 13:00:00,217 - ERROR    - syncCassElastic.py  :64 - A file lastRunTime.log should exists with the last run date in the format YYYYMMDD HH:MM
2015-02-12 13:00:59,669 - INFO     - main.py             :14 - starting sync daemon
2015-02-12 13:00:59,669 - ERROR    - syncCassElastic.py  :64 - A file lastRunTime.log should exists with the last run date in the format YYYYMMDD HH:MM
2015-02-12 13:01:36,527 - INFO     - main.py             :14 - starting sync daemon
2015-02-12 13:02:18,355 - INFO     - main.py             :14 - starting sync daemon
2015-02-12 13:02:42,047 - INFO     - main.py             :14 - starting sync daemon
